site:
    title: 雾里影 雨中泪
    subtitle: All those moments will be lost in time.
    # logo: -/images/avatar.jpg
    limit: 10
    theme: theme
    lang: zh
    url: https://kirigiri.me/
    logo: "-/images/avatar.jpg"

authors:
    me:
        name: 雾里
        intro: All those moments will be lost in time.
        avatar: -/images/avatar.jpg

build:
    port: "127.0.0.1:1313"
    # Copied files to public folder when build
    copy:
        - theme/bundle
        - theme/favicon.ico
        - theme/robots.txt
        - source/images
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin master
